name: CI

on: 
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get the repo code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build the project
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push the Api image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: runtime
          push: true
          tags: |
            ghcr.io/ngoluuquocdat/url-shortener-api:latest
            ghcr.io/ngoluuquocdat/url-shortener-api:${{ github.sha }}

      - name: Build and push the Migrator image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: migrator
          push: true
          tags: |
            ghcr.io/ngoluuquocdat/url-shortener-api:migrator
  
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRV_KEY }}
          publickey: ${{ secrets.VPS_SSH_PUB_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            cd /home/dat/app
            docker compose --env-file .env.prod -f docker-compose.yml -f docker-compose.prod.yml pull
            docker compose --env-file .env.prod -f docker-compose.yml -f docker-compose.prod.yml up -d